#ifndef SPECTRE_WINDOWING_SYSTEM_FLAGS
#define SPECTRE_WINDOWING_SYSTEM_FLAGS

#if defined __linux__ || __APPLE__
    #define SPECTRE_MOUSE_BUTTON_PRESS XCB_EVENT_MASK_BUTTON_PRESS
#elif defined _WIN32
    #define SPECTRE_MOUSE_BUTTON_PRESS 0
#endif

#endif